// LOGIN
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

// LOGOUT
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";

// REGISTER
export const FIRST_NAME_CHANGED = "FIRST_NAME_CHANGED";
export const LAST_NAME_CHANGED = "LAST_NAME_CHANGED";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const AVATAR_CHANGED = "AVATAR_CHANGED";

// FETCH LOGGED IN USER
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const SET_USER_SUCCESS = "SET_USER_SUCCESS";

export const GET_CURRENT_USER = "GET_CURRENT_USER";

// HOME SCREEN
export const SEARCH_TEXT_CHANGED = "SEARCH_TEXT_CHANGED";

// ADD CLIENT
export const CLIENT_NAME_CHANGED = "CLIENT_NAME_CHANGED";
export const CLIENT_ADDRESS_CHANGED = "CLIENT_ADDRESS_CHANGED";
export const CLIENT_PHONE_NUMBER_CHANGED = "CLIENT_PHONE_NUMBER_CHANGED";
export const CLIENT_EMAIL_CHANGED = "CLIENT_EMAIL_CHANGED";
export const CLIENT_BUDGET_CHANGED = "CLIENT_BUDGET_CHANGED";
export const CLIENT_PREFERRED_AREAS_CHANGED = "CLIENT_PREFERRED_AREAS_CHANGED";
export const CLIENT_NOTES_CHANGED = "CLIENT_NOTES_CHANGED";

export const DELETE_CLIENT_REQUESTED = "DELETE_CLIENT_REQUESTED";
export const DELETE_CLIENT_SUCCEEDED = "DELETE_CLIENT_SUCCEEDED";
export const DELETE_CLIENT_FAILED = "DELETE_CLIENT_FAILED";
