// LOGIN
export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED";
export const LOGIN_USER_SUCCEEDED = "LOGIN_USER_SUCCEEDED";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

// LOGOUT
export const LOGOUT_USER_REQUESTED = "LOGOUT_USER_REQUESTED";
export const LOGOUT_USER_SUCCEEDED = "LOGOUT_USER_SUCCEEDED";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";

// REGISTER
export const FIRST_NAME_CHANGED = "FIRST_NAME_CHANGED";
export const LAST_NAME_CHANGED = "LAST_NAME_CHANGED";
export const REGISTER_USER_REQUESTED = "REGISTER_USER_REQUESTED";
export const REGISTER_USER_SUCCEEDED = "REGISTER_USER_SUCCEEDED";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const AVATAR_CHANGED = "AVATAR_CHANGED";

// FETCH LOGGED IN USER
export const FETCH_USER_REQUESTED = "FETCH_USER_REQUESTED";
export const FETCH_USER_SUCCEEDED = "FETCH_USER_SUCCEEDED";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

// ADD CLIENT
export const CLIENT_NAME_CHANGED = "CLIENT_NAME_CHANGED";
export const CLIENT_ADDRESS_CHANGED = "CLIENT_ADDRESS_CHANGED";
export const CLIENT_PHONE_NUMBER_CHANGED = "CLIENT_PHONE_NUMBER_CHANGED";
export const CLIENT_EMAIL_CHANGED = "CLIENT_EMAIL_CHANGED";
export const CLIENT_NOTES_CHANGED = "CLIENT_NOTES_CHANGED";

// DELETE CLIENT
export const DELETE_CLIENT_REQUESTED = "DELETE_CLIENT_REQUESTED";
export const DELETE_CLIENT_SUCCEEDED = "DELETE_CLIENT_SUCCEEDED";
export const DELETE_CLIENT_FAILED = "DELETE_CLIENT_FAILED";

// UPDATE CLIENT
export const UPDATE_CLIENT_REQUESTED = "UPDATE_CLIENT_REQUESTED";
export const UPDATE_CLIENT_SUCCEEDED = "UPDATE_CLIENT_SUCCEEDED";
export const UPDATE_CLIENT_FAILED = "UPDATE_CLIENT_FAILED";

// ADD CLIENT
export const ADD_CLIENT_REQUESTED = "ADD_CLIENT_REQUESTED";
export const ADD_CLIENT_SUCCEEDED = "ADD_CLIENT_SUCCEEDED";
export const ADD_CLIENT_FAILED = "ADD_CLIENT_FAILED";
