export enum Routes {
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",
  HOME_SCREEN = "HOME_SCREEN",
  SCHEDULE_SCREEN = "SCHEDULE_SCREEN",
  NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN",
  PROFILE_SCREEN = "PROFILE_SCREEN",
  DASHBOARD_TABS = "DASHBOARD_TABS",
  ADD_NEW_CLIENT_SCREEN = "ADD_NEW_CLIENT_SCREEN",
  CLIENT_DETAIL_SCREEN = "CLIENT_DETAIL_SCREEN",
  CLIENT_UPDATE_SCREEN = "CLIENT_UPDATE_SCREEN",
}
