export enum Routes {
  AUTH_NAVIGATOR = "AUTH_NAVIGATOR",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",

  DASHBOARD_TAB_NAVIGATOR = "DASHBOARD_TAB_NAVIGATOR",
  FEED_SCREEN = "FEED_SCREEN",
  PROFILE_SCREEN = "PROFILE_SCREEN",
  POST_SCREEN = "POST_SCREEN",

  FRIENDS_TAB_NAVIGATOR = "FRIENDS_TAB_NAVIGATOR",
  FIND_FRIENDS_SCREEN = "FIND_FRIENDS_SCREEN",
  FRIENDS_LIST_SCREEN = "FRIENDS_LIST_SCREEN",

  MESSAGE_NAVIGATOR = "MESSAGE_NAVIGATOR",
  MESSAGE_SCREEN = "MESSAGE_SCREEN",
  MESSAGE_DETAILS_SCREEN = "MESSAGE_DETAILS_SCREEN",

  MESSAGE_MODALS = "MESSAGE_MODALS",
  CREATE_MESSAGE_SCREEN = "CREATE_MESSAGE_SCREEN",

  NOTIFICATION_NAVIGATOR = "NOTIFICATION_NAVIGATOR",
  NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN",
  NOTIFICATION_DETAILS = "NOTIFICATION_DETAILS",
}
