enum Routes {
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",
  FEED_SCREEN = "FEED_SCREEN",
  SCHEDULE_SCREEN = "SCHEDULE_SCREEN",
  NOTIFICATION_SCREEN = "NOTIFICATION_SCREEN",
  PROFILE_SCREEN = "PROFILE_SCREEN",
  DASHBOARD_TABS = "DASHBOARD_TABS",
  POST_SCREEN = "POST_SCREEN",
  FIND_FRIENDS_SCREEN = "FIND_FRIENDS_SCREEN",
}

export default Routes;
